name: Eslint
on:
  push:
    branches: 
      - '*'
    paths-ignore:
      - '.github/**'
      - '*.md'
      - 'Procfile'  
      - 'pnpm-lock.yaml'
      - 'node_modules/**'
  pull_request:
    branches: 
      - '*'
    paths-ignore:
      - '.github/**'
      - '*.md'
      - 'Procfile'  
      - 'pnpm-lock.yaml'
      - 'node_modules/**'
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run eslint